name: rewards_frontend
description: Plataforma Flutter para gestion de recompensas.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.2
  dio: ^5.7.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  equatable: ^2.0.5
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
